import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shohidul Protfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-gradient-to-b from-blue-100 to-red-500 flex flex-col ">
          <div className="h-24">
            <Navbar />
          </div>
          <div className="flex-grow">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
